[package]
name = "tdd-exercise"
version = "0.1.0"
authors = ["Toro <nicholas.torobian@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
